# Generated by Django 3.2.5 on 2021-07-22 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210720_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
    ]
