# Generated by Django 3.2.5 on 2021-07-22 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pedido', to='api.city'),
        ),
    ]
