# Generated by Django 3.2.5 on 2021-07-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210722_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='country',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='country', to='api.country'),
        ),
    ]
