# Generated by Django 3.2.5 on 2021-07-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210722_1510'),
        ('api', '0012_auto_20210722_1515'),
    ]

    operations = [
    ]
