# Generated by Django 3.2.5 on 2021-07-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_0012_auto_20210722_1510_0012_auto_20210722_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='path',
            field=models.CharField(max_length=50),
        ),
    ]
