# Generated by Django 3.2.5 on 2021-07-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_routes_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(default='', null=True, related_name='category', to='api.Category'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='country',
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.ManyToManyField(default='', null=True, related_name='country', to='api.Country'),
        ),
    ]
