# Generated by Django 3.2.5 on 2021-07-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210722_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(related_name='category', to='api.Category'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='city',
        ),
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.ManyToManyField(related_name='city', to='api.City'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='country',
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.ManyToManyField(related_name='country', to='api.Country'),
        ),
    ]
