# Generated by Django 3.2.5 on 2021-07-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210722_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='path',
            field=models.CharField(max_length=100),
        ),
    ]
