# Generated by Django 3.2.5 on 2021-07-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_routes_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='path',
            field=models.CharField(max_length=100),
        ),
    ]
