# Generated by Django 3.2.5 on 2021-07-26 23:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_routes_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
