# Generated by Django 3.2.5 on 2021-07-26 23:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_routes_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitrine',
            name='routes',
        ),
        migrations.AddField(
            model_name='vitrine',
            name='routes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default='{}', size=None),
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
    ]
