# Generated by Django 3.2.5 on 2021-07-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210726_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='observacao',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
